name: Generate NPM SBOM

on:
  push:
    branches: 
      - "main"
      - "workflow-dev-test"  # TODO: remove 
    paths:
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:

env:
  NODE_VERSION: '18.7'
  REGISTRY_URL: 'https://npm.pkg.github.com/'
  SBOM_NAME: 'frontend.json'
  PRODUCT_PATH: './'

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node SDK
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}
          
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> .npmrc
          echo "CI=true" >> $GITHUB_ENV
          npm ci

      - name: Install cyclonedx-npm
        run: |
          npm install --global @cyclonedx/cyclonedx-npm

      - name: Generate SBOM
        run: |
          cyclonedx-npm --output-format json --output-file sbom.json
          
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SBOM_NAME }}
          path: ${{ env.PRODUCT_PATH }}/sbom.json