name: Generate NPM SBOM

on:
  push:
    branches: 
      - "main"
      - "workflow-dev-test"  # TODO: remove 
    # paths:
    #   - "package.json"
    #   - "package-lock.json"
  workflow_dispatch:

env:
  NODE_VERSION: '18.7'
  REGISTRY_URL: 'https://npm.pkg.github.com/'
  PRODUCT_NAME: 'frontend'
  PRODUCT_PATH: './'
  SBOM_NAME: 'frontend.json'

permissions:
  contents: read

jobs:
  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    permissions:
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node SDK
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY_URL }}
          
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ github.token }}" >> .npmrc
          echo "CI=true" >> $GITHUB_ENV
          npm ci

      - name: Install cyclonedx-npm
        run: |
          npm install --global @cyclonedx/cyclonedx-npm

      - name: Generate SBOM
        run: |
          cyclonedx-npm --output-format json --output-file bom.json
          
      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SBOM_NAME }}
          path: ${{ env.PRODUCT_PATH }}/bom.json

  upload-sbom:
    if: github.repository == 'iliescuioana/syson' # TODO: edit
    runs-on: ubuntu-latest
    needs: [ 'generate-sbom' ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.SBOM_NAME }}

      - name: Extract version
        id: version
        run: |
          VERSION="$(jq -r '.metadata.component.version' < bom.json)"
          echo "version=$(echo ${VERSION})" >> $GITHUB_OUTPUT
      - uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5 # v3.1.0
        with:
          serverHostname: 'sbom.eclipse.org'
          apiKey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          projectName: ${{ env.PRODUCT_NAME }}
          projectVersion: ${{ steps.version.outputs.version }}
          bomFilename: 'bom.json'
          parent: '1b099ee7-62ee-48e1-986b-b7f0309dd344'
          autoCreate: true