name: Generate SBOM

on:
  workflow_dispatch:
  push:
    branches:
      - workflow-dev-test

jobs:
  generate-backend-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: |
          echo "Hello World"