name: Generate Maven SBOM

on:
  push:
    branches: 
      - "main"
    paths:
      - 'backend/application/**/pom.xml'
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  PRODUCT_NAME: 'application'
  PRODUCT_PATH: 'backend/application'
  PLUGIN_VERSION: '2.7.8'
  SBOM_NAME: 'backend_application_sbom.json'
  SBOM_TYPE: 'makeAggregateBom'

permissions:
  contents: read

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate sbom
        env:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:$PLUGIN_VERSION:$SBOM_TYPE -f "$PRODUCT_PATH/pom.xml" --settings settings.xml

      - name: Upload sbom
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SBOM_NAME }}
          path: ${{ env.PRODUCT_PATH }}/target/bom.json

  upload-sbom:
    if: github.repository == 'iliescuioana/syson' # TODO:edit
    runs-on: ubuntu-latest
    needs: [ 'generate-sbom' ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.SBOM_NAME }}

      - name: Extract version
        id: version
        run: |
          VERSION="$(jq -r '.metadata.component.version' < bom.json)"
          echo "version=$(echo ${VERSION})" >> $GITHUB_OUTPUT
      - uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5 # v3.1.0
        with:
          serverHostname: 'sbom.eclipse.org'
          apiKey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          projectName: ${{ env.PRODUCT_NAME }}
          projectVersion: ${{ steps.version.outputs.version }}
          bomFilename: 'bom.json'
          parent: '5ff00cf9-9edd-4c44-b601-a332664f3ec5'
          autoCreate: true