name: Generate SBOM

on:
  push:
    branches:
      - workflow-dev-test
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: |
          echo "Hello World"