name: Generate SBOM

on:
  push:
    branches:
      - workflow-dev-test
  workflow_dispatch:

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'temurin'
  PRODUCT_PATH: 'backend/application'
  SBOM_TYPE: 'makeAggregateBom'
  SBOM_NAME: 'backend_application_sbom.json'

permissions:
  contents: read

jobs:
  generate-backend-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Generate sbom
        env:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn org.cyclonedx:cyclonedx-maven-plugin:2.7.8:$SBOM_TYPE -f "$PRODUCT_PATH/pom.xml" --settings settings.xml

      - name: Upload sbom
        uses: actions/upload-artifact@v3
        with:
          name: backend-end-sbom.json
          path: ${{ env.PRODUCT_PATH }}/target/${{ env.SBOM_NAME }}